### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by billbarni** [rvep/dev_backend#1]
An update to maybe add all/some of the following files to the ignore list:
1. `rvep.spring.log.1`
2. `gradle/wrapper/*`
3. `gradlew.bat`
4. `gradlew`

**Comment by borysn** [comment]
@billbarni thanks for sharing. I'm going to keep the gradle wrapper files around for now, I can update the ignore for the log files though.

**Comment by borysn** [comment]
@billbarni git ignore has been updated, I'm going to close out the issue
