### ISSUE TITLE
Update README.md to include Firebase how to's.

### ISSUE THREAD

**Issue by billbarni** [rvep/dev_backend#2]
Update the `README.md` to include instructions to set a Google Firebase instance and attach it to the project.

**Comment by borysn** [comment]
@billbarni yes, I've been meaning to that! Thank you for bringing it to my attention though, I'll try to get that out later tonight, or tomorrow. Probably add a wiki page, and link to it in the readme.

**Comment by billbarni** [comment]
Sorry to bother you with this. The project is really amazing. I wish I had the skills to fork and help you. I was trying to implement an alternative security system without firebase, with no success. Anyway, thanks for sharing this project.

**Comment by borysn** [comment]
@billbarni no need for apologies, it's quite alright. The skills just take time to build up, I'm sure you have them started already. It's really just about learning the frameworks and libraries that are used in the project, for the dev_backend project, it's all about spring, jpa/hibernate, and core java. The spring framework is huge, but this project only makes use of spring-boot, spring-data-jpa, and spring-data-rest.

There could be a misunderstanding to clear up about the structure of the application, it could lead to a better development experience, so feel free to ask questions. In a nutshell this is a restful application using an appserver serving a rest api, and a front end web client that makes requests to the app server.

As far as an alternative security system, were you trying to do username and password login? I would still use firebase for that. Firebase just makes things easy.

As far as application security, the only measure right now is generating/validating api tokens. It's in an early stage of development still, but good enough to move on. Eventually I need to implement some type of session management, and expiration for tokens. And obviously https at some point if the project is ever to be hosted outside of a dev environment somewhere. For the time being, I'm just moving forward with functionality.

**Comment by billbarni** [comment]
Yes, I was trying to implement a login/password system, keeping JJWT tokens and most of the functionality intact in the Angular2 side. The reason behind that is that I wanted an 100% offline application.

**Comment by borysn** [comment]
@billbarni I gotcha, I can try to outline this for you here in a nutshell.
1. augment database
   - create new table with rvep_user_id as foreign key
     - or, add password field to user_profile table
     - store as CHAR or more likely BINARY
   - use eclipse or another tool to regenerate the pojos and make any necessary changes to affected dao's.
2. create a registration component for the rest api
   - create a new rest controller for registration
   - create a service for storing  registration info
   - perform any validations necessary
3. create a login component for the rest api
   - another new rest controller
   - create a service for verifying login info
   - generate and return api token on successful login
4. create frontend ui components
   - registration component
   - login component
   - services to make rest api requests
     - processing and redirecting
5. security
   - https obviously, don't want login info flying across the network accessible to anyone.
   - hash passwords front-end, and store hashed passwords backend

**Comment by billbarni** [comment]
Thanks. I'm really stuck in parts 3 and 4.
Building a nice-looking component that works like the 'FirebaseAuthService' (`firebaseauth.service.ts`) is the challenge.
Well. Thanks for all the info! Keep up the amazing project.

**Comment by borysn** [comment]
@billbarni the magic there happens with subscribing to the angularfire2 package auth state. The angularfire2 package handles all of the firebase auth state subscription, so it makes everything easy and clean.

What you might want to do is create a login service that has an async function. This function will make the http request to the rest api, and await return a promise which you can subscribe to. Your login button will then hook a service call to fire that request and subscribe to the awaited promise. 

You can check out the registration components for a good example. The hooks to fire these requests are just done using service calls awaiting the firebase auth state subscription, it's not done straight through a button.
1. [auth.service.ts](https://github.com/rvep/dev_frontend/blob/master/src/rvep/signin/shared/services/auth.service.ts) - subscribe to registration promise reurn
2. [registeruser.service.ts](https://github.com/rvep/dev_frontend/blob/master/src/rvep/signin/shared/services/registeruser.service.ts) - rest api http requests example using async await and promise return

The rest should be simple, your subscription to that promise will just process the response your rest controller generates (i.e. failed login, or success and redirect)
